### ISSUE TITLE
Map markers dissolving an reapearing randomly on zoom and pan

### ISSUE THREAD

**Issue by clemenslermen** [stefanocudini/leaflet-list-markers#1]
Hi Stefan, big thanks for this plugin. 
I'm making great use of it. One thing that i can't get my head around is the the behavior that sometimes map marker just disappear, and then on interaction with the map element reappear again.
It happens on zoom and pan.
Do you perhaps know where the problem here is?

**Comment by stefanocudini** [comment]
the plugin work with map vents *zoomend* and *moveend* if you have too markers in the map the delay depends from compuiting new list
