### ISSUE TITLE
Too many markers hides zoom control

### ISSUE THREAD

**Issue by denpanosekai** [stefanocudini/leaflet-list-markers#2]
See image. Should be options to put this list at the bottom, in a flat horizontal format, or a max number of markers.

![markers](https://cloud.githubusercontent.com/assets/4294534/3147893/1a08b29c-ea5a-11e3-9df2-56bf3188f2fb.png)

**Comment by stefanocudini** [comment]
https://github.com/stefanocudini/leaflet-list-markers/blob/master/src/leaflet-list-markers.js#L16

*position: 'topleft'*

**Comment by n0099** [comment]
```js
new L.Control.ListMarkers({ position: 'topright', ...restOptions })
```
