### ISSUE TITLE
Use of deprecated properties

### ISSUE THREAD

**Issue by Berkmann18** [stefanocudini/leaflet-list-markers#5]
After using this plugin within my Leaflet app, I keep on seeing the following warning:
```console
leaflet.js:5 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at y (https://unpkg.com/leaflet@1.2.0/dist/leaflet.js:5:2048)
    at Function.v.extend (https://unpkg.com/leaflet@1.2.0/dist/leaflet.js:5:14706)
    at http://localhost:63342/CS3821/lib/leaflet-list-markers/dist/leaflet-list-markers.min.js:17:45
    at http://localhost:63342/CS3821/lib/leaflet-list-markers/dist/leaflet-list-markers.min.js:17:2811
```
The code I have in my script is the following:
```js
let list = new L.Control.ListMarkers({layer: markersLayer, itemIcon: null});

list.on('item-mouseover', (e) => {
    e.layer.setIcon(L.icon({
        iconUrl: '../lib/leaflet-list-markers/images/select-marker.png'
    }));
}).on('item-mouseout', (e) => {
    e.layer.setIcon(L.icon({
        iconUrl: getPath() + 'marker-icon.png'
    }));
});
map.addControl(list);
```

## What I did
I tried finding a way to fix that but I can't seem to find anything unlike the marker icon issue which I'm trying to fix (incoming issue or PR on that) (everything else on the map works fine).

## Environment
I have this issue on both Opera, Chrome and Firefox (using either ArchLinux or Windows 7).

EDIT: I found a fairly simple work-around to restore the correct icon on the markers after "mousing-out" but I **still get the warning**.

**Comment by stefanocudini** [comment]
solved from version 0.1.0
